import { Cigar } from './types';
export const CIGARS_DATA: Cigar[] = [
  {
    id: 1,
    name: 'ANTONIO GIMENEZ CHURCHILL',
    image: 'images/ANTONIO GIMENEZ CHURCHILL.png',
    detailsImage: 'images/ANTONIO GIMENEZ CHURCHILL details.png',
    price: '₱1,200.00',
    origin: 'Philippines',
    profile: 'Mild - Medium',
    vitola: '7x47 Churchill',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'An extended format for the full experience, the AG Churchill spans 7" × 47 and delivers consistent richness from foot to nub. Its Java wrapper and Isabela binder encase a premium filler blend that smokes bold and spicy. This long-format cigar is ideal for aficionados craving a classic, uninterrupted full-bodied session.',
  },
  {
    id: 2,
    name: 'COHIBA PURO DOMINICANA ROBUSTO',
    image: '/images/COHIBA PURO DOMINICANA ROBUSTO.png',
    detailsImage: '/images/COHIBA PURO DOMINICANA ROBUSTO details.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Medium-Full',
    vitola: 'Robusto',
    wrapper: 'Dominican',
    binder: 'Dominican',
    filler: 'Dominican',
    description: 'A testament to Dominican craftsmanship, the Cohiba Puro Dominicana Robusto is a pure expression of Dominican tobacco.',
  },
  {
    id: 3,
    name: 'DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS',
    image: '/images/DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS.png',
    detailsImage: '/images/DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS details.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Full',
    vitola: 'Robusto Tubos',
    wrapper: 'Ecuadorian Sun Grown',
    binder: 'Dominican',
    filler: 'Dominican',
    description: 'The Davidoff Millennium Blend Robusto Tubos represents luxury and sophistication. Features an Ecuadorian Sun Grown wrapper.',
  },
  {
    id: 4,
    name: 'DAVIDOFF WINSTON CHURCHILL ROBUSTO',
    image: '/images/DAVIDOFF WINSTON CHURCHILL ROBUSTO.png',
    detailsImage: '/images/DAVIDOFF WINSTON CHURCHILL ROBUSTO details.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Medium',
    vitola: 'Robusto',
    wrapper: 'Ecuadorian',
    binder: 'Mexican',
    filler: 'Dominican & Nicaraguan',
    description: 'Named after the legendary statesman, the Davidoff Winston Churchill Robusto embodies sophistication and character.',
  },
  {
    id: 5,
    name: 'FLOR DE FILIPINAS CORONA SUMATRA',
    image: '/images/FLOR DE FILIPINAS CORONA SUMATRA.png',
    detailsImage: '/images/FLOR DE FILIPINAS CORONA SUMATRA details.png',
    price: '₱800.00',
    origin: 'Philippines',
    profile: 'Mild - Medium',
    vitola: '5.5x44 Corona',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'Classic and aromatic, the Flor De Filipinas Corona Sumatra combines tradition with balance. Measuring 5.5 × 44, it\'s wrapped in a fine Sumatra-grown Java leaf with a signature "Sarah" binder, giving it a slightly sweet edge. Its Isabela-Sarah filler blend produces a mellow yet flavorful smoke—a comforting companion for daily',
  },
  {
    id: 6,
    name: 'INDEPENDENCIA 1898 ROBUSTO',
    image: '/images/INDEPENDENCIA 1898 ROBUSTO.png',
    detailsImage: '/images/INDEPENDENCIA 1898 ROBUSTO details.png',
    price: '₱1,000.00',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: '5x52 Robusto',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'Celebrating Filipino pride, the 1898 Robusto is a symbol of heritage and flavor. Wrapped in smooth Indonesian Java and filled with rich Isabela "pais" tobacco, it delivers a balanced, full-bodied profile. Measuring 5 × 52, this Robusto offers a creamy smoke with earthy undertones—ideal for both celebratory and contemplative moments.',
  },
  {
    id: 7,
    name: 'Rocky Patel Cargo Torpedo',
    image: '/images/Rocky Patel Cargo Torpedo.png',
    detailsImage: '/images/Rocky Patel Cargo Torpedo details.png',
    price: '₱1,400.00',
    origin: 'Nicaragua',
    profile: 'Medium',
    vitola: '6x52 Torpedo',
    wrapper: 'Ecuador Connecticut',
    binder: 'Nicaragua',
    filler: 'Nicaraguan',
    description: 'The Rocky Patel Cargo Torpedo is a sleeper hit in the Rocky Patel catalog — an accessible, well-constructed cigar that punches above its price point. Draped in a silky Ecuador Sumatra wrapper, it opens with dry cedar and toasted almond notes that quickly deepen into seasoned wood and a faint black-pepper spice. The torpedo tip concentrates the smoke and brings forward an energetic core of cocoa and subtle espresso, while the Nicaraguan filler gives the blend a pleasant earthiness. Construction is consistently reliable, producing a steady draw and an even, long-lasting burn that makes Cargo a dependable daily smoke for both new and experienced smokers.',
  },
  {
    id: 8,
    name: '1881 PERIQUE BOLD SHORT ROBUSTO MADURO',
    image: '/images/1881 PERIQUE BOLD SHORT ROBUSTO MADURO.jpg',
    detailsImage: '/images/1881 PERIQUE BOLD SHORT ROBUSTO MADURO details.jpg',
    price: '₱2,000.00',
    origin: 'Philippines',
    profile: 'Full',
    vitola: '4x55 Robusto',
    wrapper: 'Dominican Republic',
    binder: 'Philippines',
    filler: 'Brazil',
    description: 'Tabacalera proudly presents the 1881 Perique Bold, a premium cigar crafted from a distinctive blend of 15-year vintage tobaccos and rare Louisiana-grown Perique, meticulously fermented in oak whiskey casks to enhance its depth and strength. This innovative fusion delivers a remarkably smooth smoking experience, enriched by bold peppery notes, hints of subtle sweetness, and a long-lingering spice that finishes with refined elegance.',
  },
  {
    id: 9,
    name: 'TABACALERA GRAN RESERVA',
    image: '/images/TABACALERA GRAN RESERVA.jpg',
    detailsImage: '/images/TABACALERA GRAN RESERVA details.jpg',
    price: '₱2,300.00',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: '5x52 Robusto',
    wrapper: 'Philippines',
    binder: 'Philippines',
    filler: 'Philippines, Brazil, Dominican Republic',
    description: 'Crafted for the true cigar aficionado, the Tabacalera Gran Reserva embodies sophistication, heritage, and complexity. Expertly rolled by masters with over 50 years of experience, this exceptional cigar represents the pinnacle of craftsmanship. Its refined blend features Philippine leaf aged for 20 years, harmoniously combined with Brazilian and Dominican tobaccos matured for 15 years. The result is a smooth, luxurious smoke with remarkable depth and a satisfyingly long finish that reveals rich layers of flavor. The Gran Reserva delivers elegant notes of earth, cedar, and a subtle spice—ideal for those long, reflective moments.',
  },
  {
    id: 10,
    name: 'ALEC BRADLEY SUPERSTITION',
    image: '/images/ALEC BRADLEY SUPERSTITION.png',
    detailsImage: '/images/ALEC BRADLEY SUPERSTITION details.png',
    price: '₱1,400.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '6.1x54 Toro Torpedo',
    wrapper: 'Habano / Nicaraguan Jalapa',
    binder: 'Sumatra',
    filler: 'Dominican / Hondura / Nicaragua',
    description: 'A sophisticated blend featuring a Habano wrapper with Nicaraguan Jalapa, complemented by a Sumatra binder and a complex filler blend from Dominican Republic, Honduras, and Nicaragua.',
  }
];
