import { Cigar } from './types';
export const CIGARS_DATA: Cigar[] = [
  {
    id: 1,
    name: 'ANTONIO GIMENEZ CHURCHILL',
    image: '/images/ANTONIO GIMENEZ CHURCHILL.png',
    price: '₱1,200.00',
    origin: 'Philippines',
    profile: 'Mild - Medium',
    vitola: '7x47 Churchill',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'An extended format for the full experience, the AG Churchill spans 7" × 47 and delivers consistent richness from foot to nub. Its Java wrapper and Isabela binder encase a premium filler blend that smokes bold and spicy. This long-format cigar is ideal for aficionados craving a classic, uninterrupted full-bodied session.',
  },
  {
    id: 2,
    name: 'COHIBA PURO DOMINICANA ROBUSTO',
    image: '/images/COHIBA PURO DOMINICANA ROBUSTO.png',
    price: '₱3,500.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '5.5x50 Robusto',
    wrapper: 'Habano',
    binder: 'Dominican Republic',
    filler: 'Dominican Republic',
    description: 'The Cohiba Puro Dominicana lives up to its name as a 100% Dominican puro. Crafted by master blender Daniel Nunez, this robust cigar begins with an oily, toothsome Dominican Habano wrapper cloaking a Dominican binder and long-filler blend. To maximize flavor, each tobacco leaf is patiently aged en tercio in charcoal-lined barrels, imparting a distinctive oaky taste. Once rolled, the medium-to-full bodied cigar undergoes further aging, allowing its complex flavors to marry. The result is a powerful yet refined balance of leathery spice. As Cohiba\'s definitive super-premium robusto, the Puro Dominicana delivers full-flavored satisfaction down to the nub. Try pairing it with a Spiked Egg Nog for a perfect match.',
  },
  {
    id: 3,
    name: 'DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS',
    image: '/images/DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS.png',
    price: '₱4,000.00',
    origin: 'Dominican Republic',
    profile: 'Medium',
    vitola: '5 1/4x50 Robusto',
    wrapper: 'Ecuadorian Sungrown',
    binder: 'Dominican Republic',
    filler: 'Dominican Republic',
    description: 'The Davidoff Millennium Blend Series Robusto Tubos harmoniously blends ligero and visus grade leaves, resulting in deep, aromatic notes of cedar, earth, and spice. This expertly crafted cigar features a zesty white-pepper spice that is tempered and complemented by a creamy, earthy undercurrent and a trace of enticing cocoa sweetness. Dressed in a silky, reddish Ecuadorian Sungrown wrapper over a Dominican binder and filler, the Millennium Robusto Tubos will appeal to both novice and veteran cigar enthusiasts. This cigar pairs exceptionally well with a whisky-based cocktail, making it an ideal after-hours indulgence.',
  },
  {
    id: 4,
    name: 'DAVIDOFF WINSTON CHURCHILL ROBUSTO',
    image: '/images/DAVIDOFF WINSTON CHURCHILL ROBUSTO.png',
    price: '₱3,800.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '5 1/4x52 Robusto',
    wrapper: 'Ecuador',
    binder: 'Negro San Andres, Mexico',
    filler: 'Dominican Republic and Nicaragua',
    description: 'Indulge in the Davidoff Winston Churchill Robusto, where a blend of Dominican Republic, Nicaraguan, and Mexican tobaccos, complemented by an Ecuadorian wrapper, creates a harmonious fusion of leather, cream, spice, and dark coffee flavors, striking a flawless equilibrium between complexity and potency. The hint of cedar\'s natural sweetness in the Davidoff Winston Churchill - "The Original Series" pairs exquisitely with whiskies like Glenmorangie or Macallan Amber, offering a delightful combination of flavors.',
  },
  {
    id: 5,
    name: 'FLOR DE FILIPINAS CORONA SUMATRA',
    image: '/images/FLOR DE FILIPINAS CORONA SUMATRA.png',
    price: '₱800.00',
    origin: 'Philippines',
    profile: 'Mild - Medium',
    vitola: '5.5x44 Corona',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'Classic and aromatic, the Flor De Filipinas Corona Sumatra combines tradition with balance. Measuring 5.5 × 44, it\'s wrapped in a fine Sumatra-grown Java leaf with a signature "Sarah" binder, giving it a slightly sweet edge. Its Isabela-Sarah filler blend produces a mellow yet flavorful smoke—a comforting companion for daily',
  },
  {
    id: 6,
    name: 'INDEPENDENCIA 1898 ROBUSTO',
    image: '/images/INDEPENDENCIA 1898 ROBUSTO.png',
    price: '₱1,000.00',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: '5x52 Robusto',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'Celebrating Filipino pride, the 1898 Robusto is a symbol of heritage and flavor. Wrapped in smooth Indonesian Java and filled with rich Isabela "pais" tobacco, it delivers a balanced, full-bodied profile. Measuring 5 × 52, this Robusto offers a creamy smoke with earthy undertones—ideal for both celebratory and contemplative moments.',
  },
  {
    id: 7,
    name: 'Rocky Patel Cargo Torpedo',
    image: '/images/Rocky Patel Cargo Torpedo.png',
    price: '₱1,400.00',
    origin: 'Nicaragua',
    profile: 'Medium',
    vitola: '6x52 Torpedo',
    wrapper: 'Ecuador Connecticut',
    binder: 'Nicaragua',
    filler: 'Nicaraguan',
    description: 'The Rocky Patel Cargo Torpedo is a sleeper hit in the Rocky Patel catalog — an accessible, well-constructed cigar that punches above its price point. Draped in a silky Ecuador Sumatra wrapper, it opens with dry cedar and toasted almond notes that quickly deepen into seasoned wood and a faint black-pepper spice. The torpedo tip concentrates the smoke and brings forward an energetic core of cocoa and subtle espresso, while the Nicaraguan filler gives the blend a pleasant earthiness. Construction is consistently reliable, producing a steady draw and an even, long-lasting burn that makes Cargo a dependable daily smoke for both new and experienced smokers.',
  },
  {
    id: 8,
    name: '1881 PERIQUE BOLD SHORT ROBUSTO MADURO',
    image: '/images/1881 PERIQUE BOLD SHORT ROBUSTO MADURO.jpg',
    price: '₱2,000.00',
    origin: 'Philippines',
    profile: 'Full',
    vitola: '4x55 Robusto',
    wrapper: 'Dominican Republic',
    binder: 'Philippines',
    filler: 'Brazil',
    description: 'Tabacalera proudly presents the 1881 Perique Bold, a premium cigar crafted from a distinctive blend of 15-year vintage tobaccos and rare Louisiana-grown Perique, meticulously fermented in oak whiskey casks to enhance its depth and strength. This innovative fusion delivers a remarkably smooth smoking experience, enriched by bold peppery notes, hints of subtle sweetness, and a long-lingering spice that finishes with refined elegance.',
  },
  {
    id: 9,
    name: 'TABACALERA GRAN RESERVA',
    image: '/images/TABACALERA GRAN RESERVA.jpg',
    price: '₱2,300.00',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: '5x52 Robusto',
    wrapper: 'Philippines',
    binder: 'Philippines',
    filler: 'Philippines, Brazil, Dominican Republic',
    description: 'Crafted for the true cigar aficionado, the Tabacalera Gran Reserva embodies sophistication, heritage, and complexity. Expertly rolled by masters with over 50 years of experience, this exceptional cigar represents the pinnacle of craftsmanship. Its refined blend features Philippine leaf aged for 20 years, harmoniously combined with Brazilian and Dominican tobaccos matured for 15 years. The result is a smooth, luxurious smoke with remarkable depth and a satisfyingly long finish that reveals rich layers of flavor. The Gran Reserva delivers elegant notes of earth, cedar, and a subtle spice—ideal for those long, reflective moments.',
  },
  {
    id: 10,
    name: 'ALEC BRADLEY SUPERSTITION',
    image: '/images/ALEC BRADLEY SUPERSTITION.jpg',
    price: '₱1,400.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '6.1x54 Toro Torpedo',
    wrapper: 'Habano / Nicaraguan Jalapa',
    binder: 'Sumatra',
    filler: 'Dominican / Hondura / Nicaragua',
    description: 'A sophisticated blend featuring a Habano wrapper with Nicaraguan Jalapa, complemented by a Sumatra binder and a complex filler blend from Dominican Republic, Honduras, and Nicaragua.',
  },
  {
    id: 11,
    name: 'HC SERIES WHITE SHADE GROWN TORO',
    image: '/images/HC SERIES WHITE SHADE GROWN TORO.jpg',
    price: '₱1,400.00',
    origin: 'Honduras',
    profile: 'Mild - Medium',
    vitola: '6x60 Toro',
    wrapper: 'USA Connecticut Shade',
    binder: 'Nicaraguan',
    filler: 'Nicaraguan',
    description: 'The HS Series White Shade Grown features a silky-smooth Connecticut Shade wrapper enveloping a blend of long-filler tobaccos from Nicaragua, providing a mellow-medium body. Subtle notes of leather, cedar, spices, pepper, and caramel mingle throughout the mellow and creamy smoking experience, culminating in a smooth, sweet finish.',
  },
  {
    id: 12,
    name: 'PUNCH GRAN PURO RANCHO',
    image: '/images/PUNCH GRAN PURO RANCHO.jpg',
    price: '₱1,500.00',
    origin: 'Honduras',
    profile: 'Medium - Full',
    vitola: '5.5x54 Robusto',
    wrapper: 'Honduran (Havana Seed)',
    binder: 'Honduran',
    filler: 'Honduran',
    description: 'Punch is one of the original cigar brands developed in Honduras, proudly reflecting the country\'s long-standing tradition of expert tobacco curing. True to its name, the Punch Gran Puro Rancho delivers a bold, full-flavored smoking experience. Crafted handmade entirely from premium Honduran tobacco, this robusto offers rich, earthy, and creamy notes, wrapped in a striking Colorado Maduro wrapper. Expect a smooth yet intense profile, as flavors of cedar and earth meld seamlessly with the signature Honduran spice—making it an ideal choice for fans of fuller-bodied cigars.',
  },
  {
    id: 13,
    name: 'OLIVA SAISON MADURO TORO',
    image: '/images/OLIVA SAISON MADURO TORO.jpg',
    price: '₱1,500.00',
    origin: 'Nicaragua',
    profile: 'Medium - Full',
    vitola: '6x50 Toro',
    wrapper: 'Connecticut Broadleaf Maduro',
    binder: 'Nicaraguan',
    filler: 'Nicaraguan',
    description: 'Seeking to elevate the strength and complexity of their highly acclaimed Saison line, the team at Oliva took on the challenge—and delivered with the exceptional Oliva Saison Maduro. This bold creation features a meticulously aged blend of Nicaraguan long-fillers, all harvested in 2011 from only the finest tobacco crops grown on Oliva\'s own farms. These tobaccos are expertly bound with a premium Nicaraguan binder and finished with a dark, toothy, and robust Broadleaf Maduro wrapper that enhances both body and character. The result is a rich and harmoniously layered smoking experience, offering deep notes of cedar, sweet spice, and leather, all carried by a consistently razor-sharp burn. True to Oliva\'s reputation, the construction is flawless—firm to the touch with an even, slow draw. Medium to full-bodied in strength, Oliva Saison Maduro is an ideal companion to a glass of rye whiskey, making it a perfect choice for the discerning aficionado seeking depth, balance, and refinement.',
  },
  {
    id: 14,
    name: 'GURKHA HUDSON BAY CHURCHILL',
    image: '/images/GURKHA HUDSON BAY CHURCHILL.jpg',
    price: '₱1,900.00',
    origin: 'Nicaragua',
    profile: 'Medium',
    vitola: '7x50 Churchill',
    wrapper: 'San Andres',
    binder: 'Nicaraguan',
    filler: 'Nicaraguan',
    description: 'The Gurkha Hudson Bay cigars, part of the prestigious East India Trading Co. line from the renowned Gurkha brand, feature exquisite artwork and impeccable construction that deliver an exceptional smoking experience. Handmade in Nicaragua using a blend of Nicaraguan long-filler tobacco, Ometepe binder, and a robust San Andres wrapper, these cigars burn slowly with rich, velvety-smooth flavors of cedar, spice, and pepper. Though medium in strength, the elaborate blend and flawless craftsmanship make the Gurkha Hudson Bay an everyday premium cigar that looks and tastes extraordinary.',
  },
  {
    id: 15,
    name: 'HOYO DE MONTERREY EXCALIBUR',
    image: '/images/HOYO DE MONTERREY EXCALIBUR.jpg',
    price: '₱2,000.00',
    origin: 'Honduras',
    profile: 'Medium',
    vitola: '5.25x50',
    wrapper: 'Connecticut Broadleaf / Connecticut Shade',
    binder: 'Connecticut Broadleaf',
    filler: 'Dominican Republic / Honduras / Nicaragua',
    description: 'The Hoyo de Monterrey Excalibur is a premium, full-flavored cigar that stands in a class of its own. Handcrafted by the skilled artisans behind Hoyo de Monterrey, these cigars are made using only the top 10% of the finest tobacco from Honduras and Nicaragua. Each Excalibur cigar is carefully selected from the renowned Hoyo de Monterrey tobacco fields, and undergoes additional aging to ensure a refined and exceptional smoking experience. Regarded by many connoisseurs as one of the finest Honduran cigars available, the Excalibur offers a rich, smooth profile that is sure to satisfy the most discerning cigar enthusiasts.',
  },
  {
    id: 16,
    name: 'ALEC & BRADLEY GATEKEEPER ROBUSTO',
    image: '/images/ALEC & BRADLEY GATEKEEPER ROBUSTO.jpg',
    price: '₱2,000.00',
    origin: 'Dominican Republic',
    profile: 'Medium',
    vitola: '5x50 Robusto',
    wrapper: 'Ecuadorian Connecticut',
    binder: 'Nicaraguan',
    filler: 'Dominican Republic / Nicaraguan',
    description: 'Gatekeeper is the second line introduced by Rubin\'s sons, building on a legacy of craftsmanship and expertise. Encased in a rich Ecuadorian Habano wrapper, this cigar is complemented by a Nicaraguan binder and fillers sourced from both the Dominican Republic and Nicaragua. Its smooth, full-bodied profile offers a complex array of flavors, with prominent notes of cedar, nuts, and leather. The construction reflects the high standards of the renowned factory behind such iconic cigars as the Prensado. Gatekeeper is not just a cigar; it represents the passing of knowledge and skill from one generation to the next, a tribute to a great man\'s enduring influence.',
  },
  {
    id: 17,
    name: 'AVO XO INTERMEZZO ROBUSTO',
    image: '/images/AVO XO INTERMEZZO ROBUSTO.jpg',
    price: '₱2,000.00',
    origin: 'Dominican Republic',
    profile: 'Medium',
    vitola: '5x50 Robusto',
    wrapper: 'Ecuador Connecticut',
    binder: 'Dominican Republic',
    filler: 'Dominican Republic',
    description: 'AVO XO embodies the pinnacle of craftsmanship from the renowned AVO brand, showcasing tobaccos that have been meticulously aged for a minimum of six years to achieve exceptional quality. Dominican binders and long-fillers are elegantly wrapped in a luxurious Ecuadorian Connecticut leaf, prized for its smooth, golden appearance and sophisticated presentation. The smoking experience unfolds with an intricate blend of flavors—cedar, salted cashews, sweet molasses, charred wood, earth, leather, and delicate spices—each note seamlessly complementing the next, creating a truly remarkable sensory journey. The AVO XO Intermezzo offers both seasoned connoisseurs and newcomers a refined, balanced, and exceptionally smooth experience, exemplifying the finest in premium cigar craftsmanship.',
  },
  {
    id: 18,
    name: 'CAO FLATHEAD V660 CARB',
    image: '/images/CAO FLATHEAD V660 CARB.jpg',
    price: '₱2,300.00',
    origin: 'Nicaragua',
    profile: 'Medium - Full',
    vitola: '6x60 Gordo',
    wrapper: 'Connecticut Broadleaf',
    binder: 'Nicaragua',
    filler: 'Nicaragua',
    description: 'Borrowing inspiration from 1950\'s American muscle cars, Flathead premium cigar boasts a unique squared-off head meant to mimic an engine block. This highly unusual shape contains a bold, full-bodied blend of tobaccos. The dark Connecticut Broadleaf Maduro wrapper conceals Nicaraguan and Dominican long-fillers, secured by a Connecticut Habano binder. Notes of ripe fruit, leather and molasses culminate into a rich smoking experience that lingers long after you finish. With a 95 rating from Cigar Aficionado and named the #3 Cigar of 2015, Flathead stands out as the highest rated 60-ring cigar ever.',
  },
  {
    id: 19,
    name: 'CALDWELL THE KING IS DEAD PREMIER',
    image: '/images/CALDWELL THE KING IS DEAD PREMIER.jpg',
    price: '₱2,300.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '5.5x50 Robusto',
    wrapper: 'Dominican Republic (Negrito)',
    binder: 'Dominican',
    filler: 'Dominican',
    description: 'The Caldwell The King is Dead Premier is a distinguished premium cigar, expertly handcrafted in the Dominican Republic. Showcasing a rare Negrito wrapper, this blend is paired with a Dominican Corona binder and meticulously aged long-fillers for a complex, well-balanced experience. Upon lighting, the cigar opens with smooth notes of milk chocolate, gradually deepening into rich flavors of coffee and spice. As the profile develops, layers of cedar, earth, and subtle sweetness emerge, offering a dynamic and satisfying smoke. With a consistent nutty sweetness and an even, dependable burn, this cigar exemplifies both indulgence and craftsmanship.',
  },
  {
    id: 20,
    name: 'AVO SYNCRO RITMO TORO',
    image: '/images/AVO SYNCRO RITMO TORO.jpg',
    price: '₱2,300.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '6x54 Toro',
    wrapper: 'Ecuador Connecticut',
    binder: 'Mexico',
    filler: 'Brazil, Honduras, Nicaragua, Peru',
    description: 'Experience the exceptional Avo Syncro Ritmo, a masterpiece that showcases the perfect harmony of premium tobaccos from seven different countries. This remarkable handmade creation is elegantly wrapped in a silky Ecuadorian wrapper, demonstrating Avo\'s unparalleled blending expertise. Your journey begins with an exciting burst of bold pepper that awakens your senses, seamlessly transitioning to a perfectly balanced symphony of roasted nuts, rich cocoa, and robust black coffee notes. With each draw, you\'ll savor the creamy, sweet finish that makes this extraordinary cigar an absolute pleasure from first light to final puff. Treat yourself to the Avo Syncro Ritmo – a truly satisfying indulgence that cigar connoisseurs can\'t resist.',
  },
  {
    id: 21,
    name: 'MONTECRISTO WHITE SERIES ROTHSCHILDE',
    image: '/images/MONTECRISTO WHITE SERIES ROTHSCHILDE.jpg',
    price: '₱2,300.00',
    origin: 'Dominican Republic',
    profile: 'Medium',
    vitola: '5x52 Robusto',
    wrapper: 'Ecuador Connecticut Shade',
    binder: 'Nicaragua',
    filler: 'Dominican Republic; Nicaragua',
    description: 'Montecristo, one of the world\'s most coveted luxury brands, elevates its legendary portfolio with the bold and sumptuous Montecristo White cigar. Masterfully blending premium Dominican and Nicaraguan long fillers beneath a Connecticut-seed Ecuadorian shade grown wrapper, this exceptional smoke delivers a smooth yet robust experience that connoisseurs crave. Expertly handcrafted, this medium-bodied masterpiece unfolds with luxurious notes of supple leather, tantalizing spice, aromatic cedar, freshly baked bread, and rich cocoa. The extraordinary refinement and complexity of these flavors create such a memorable smoking journey that even aficionados who typically prefer fuller-bodied cigars will find themselves irresistibly drawn to the Montecristo White\'s sophisticated charm.',
  },
  {
    id: 22,
    name: 'MONTECRISTO PLATINUM ROBUSTO',
    image: '/images/MONTECRISTO PLATINUM ROBUSTO.jpg',
    price: '₱2,300.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '5x50 Robusto',
    wrapper: 'San Andrés',
    binder: 'Dominican Republic',
    filler: 'Dominican Republic / Nicaragua / Peru',
    description: 'The Montecristo Platinum Series cigars were crafted to give Montecristo aficionados a bolder, fuller-bodied rendition of a classic. Hand-rolled in the Dominican Republic, these premium cigars feature a lively Mexican San Andres wrapper enclosing a special blend of aged Dominican, Nicaraguan, and Peruvian long-filler tobaccos. With rich, smooth, medium-to-full bodied flavors reminiscent of earth, raisins, leather, black coffee, and wood, these exquisitely balanced, Cubanesque cigars make for the ideal after-dinner indulgence.',
  },
  {
    id: 23,
    name: 'DAVIDOFF GRAND CRU NO.3',
    image: '/images/DAVIDOFF GRAND CRU NO.3.jpg',
    price: '₱3,500.00',
    origin: 'Dominican Republic',
    profile: 'Mild - Medium',
    vitola: '5x43 Corona',
    wrapper: 'Ecuadorian',
    binder: 'Dominican Republic',
    filler: 'Dominican Republic',
    description: 'The Davidoff Grand Cru No. 3 is a classic ultra-premium cigar, rolled at Davidoff\'s renowned factory in the Dominican Republic. This sophisticated blend uses only the finest, meticulously selected tobacco leaves, resulting in a mild, lightly floral cigar with a delightful nutty finish. With its medium-bodied profile and gourmet notes of nuts, cream, spice, and cedar, the Grand Cru offers a sumptuous smoking experience. The Ecuadorian Connecticut Shade wrapper, Dominican binder, and premium Dominican filler come together seamlessly. This cigar pairs exceptionally well with a glass of Bordeaux, making it the perfect companion after a hearty lunch.',
  },
  {
    id: 24,
    name: 'ILLUSIONE EPERNAY LE MONDE',
    image: '/images/ILLUSIONE EPERNAY LE MONDE.jpg',
    price: '₱2,300.00',
    origin: 'Honduras',
    profile: 'Medium',
    vitola: '6 1/4x52 Toro',
    wrapper: 'Nicaraguan',
    binder: 'Nicaraguan',
    filler: 'Nicaraguan',
    description: 'The Illusione Epernay pays tribute to the renowned Epernay region of France, the capital of Champagne, with a blend designed to pair perfectly with a glass of champagne. This cigar offers a sweeter alternative to the original Illusione by Don Giolito. A medium-bodied smoke, it delivers straightforward notes of coffee bean, wood, and cinnamon, leaving a slightly tart, citrus-tinged aftertaste. Featuring a light, shade-grown Corojo \'99 wrapper, this Nicaraguan puro is a true masterpiece - a sublime smoking experience worthy of being counted among the best.',
  },
  {
    id: 25,
    name: 'DEADWOOD LEATHER ROSE TORPEDO',
    image: '/images/DEADWOOD LEATHER ROSE TORPEDO.jpg',
    price: '₱2,000.00',
    origin: 'Nicaragua',
    profile: 'Medium',
    vitola: '5x54 Torpedo',
    wrapper: 'Maduro',
    binder: 'Indonesian',
    filler: 'Nicaraguan',
    description: 'The Leather Rose, the spiciest addition to the Deadwood line, is just as delectable as its sister cigar, Sweet Jane, but with a bold new look. This 5" x 54 handcrafted Torpedo from Drew Estate\'s Nicaraguan factory features a voluptuous blend of sweet and aromatic tobaccos, cloaked in a dark, rustic Maduro wrapper. The sweetened wrapper leaf beautifully complements the thick notes of chocolate, coffee, wood, leather, berries, and spice that build to a grand, sweet-yet-peppery finale. Rich, spicy, and deliciously sweet, the Leather Rose is the perfect pairing for a whiskey sour.',
  },
  {
    id: 26,
    name: 'JOYA CABINETTA CHURCHILL',
    image: '/images/JOYA CABINETTA CHURCHILL.jpg',
    price: '₱2,000.00',
    origin: 'Nicaragua',
    profile: 'Mild - Medium',
    vitola: '6 7/8x48 Churchill',
    wrapper: 'Ecuadorian Connecticut Shade, Nicaraguan Habana Criollo',
    binder: 'Nicaragua',
    filler: 'Nicaragua',
    description: 'Since 1968, Joya de Nicaragua has been known for producing full-bodied, powerful cigars. However, with their Cabinetta line, they have crafted a markedly different experience - one that is creamy and mild. Cabinetta cigars feature a dark, coffee-hued Nicaraguan Criollo wrapper, blended with a creamy, light Ecuadorian Shade wrapper. This unique combination lends a complex array of flavors and aromas. In contrast to other Joya cigars, the medium-bodied Cabinetta is less demanding on the palate. Carefully selected Nicaraguan long-fillers deliver a solid, smooth smoking experience that is worthy of praise.',
  },
  {
    id: 27,
    name: 'FLAVORED PANETELAS CHERRY',
    image: '/images/FLAVORED PANETELAS CHERRY.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'N/A',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Fragrant, fruity, and pleasantly smooth, Flor de Filipinas Cherry Panetela is a vibrant choice for those who enjoy a sweeter, more playful smoking experience. It\'s a flavorful companion to breezy afternoons or relaxed hangouts.',
  },
  {
    id: 28,
    name: 'FLAVORED PANETELAS CHOCOLATE',
    image: '/images/FLAVORED PANETELAS CHOCOLATE.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'Java',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Richly aromatic and indulgently smooth, Flor de Filipinas Chocolate Panetela is a cocoa-infused treat designed for those who enjoy sweet, full-flavored smokes. A satisfying companion to coffee, dessert, or a cozy evening unwind. Deep and decadent, this 5 × 35 Panetela delivers a smooth draw layered with chocolate truffle notes. Crafted with care and wrapped in fine Java, it\'s a flavorful pleasure with every puff.',
  },
  {
    id: 29,
    name: 'FLAVORED PANETELAS HONEY',
    image: '/images/FLAVORED PANETELAS HONEY.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'N/A',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Delicately sweet and incredibly smooth, Flor de Filipinas Honey Panetela offers a gentle, golden flavor profile that\'s easy to love. Mellow with a golden nectar finish, the Honey Panetela offers a smooth draw and subtle sweetness. Easy to love and hard to put down, it\'s a gentle aromatic smoke ideal for laid-back afternoons or pairing with tea and light spirits.',
  },
  {
    id: 30,
    name: 'FLAVORED PANETELAS SPICE RUM',
    image: '/images/FLAVORED PANETELAS SPICE RUM.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'N/A',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Warm, aromatic, and full of character, Flor de Filipinas Spice Rum Panetela brings a spirited twist to the traditional cigar. Infused with notes of clove and molasses, this 5 × 35 Panetela delivers the richness of rum in a mellow, satisfying format. Perfect for nightcaps and social indulgence.',
  },
  {
    id: 31,
    name: 'FLAVORED PANETELAS VANILLA',
    image: '/images/FLAVORED PANETELAS VANILLA.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'N/A',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Aromatic, flavorful, and delightfully smooth, Flor de Filipinas Flavored Cigars are infused with rich tastes that awaken the senses and charm the palate. Offered in delicious varieties like Chocolate, Honey, Cherry, Rum, and the bestselling Vanilla, these cigars are the perfect companion to your favorite after-dinner drink or a relaxed gathering with friends. The 5x35 Vanilla Panetela delivers a light, creamy smoke with a sweet vanilla crème finish. Whether you\'re new to cigars or simply craving a dessert-like indulgence, this petite cigar is a satisfying, aromatic treat.',
  }
];
