import { Cigar } from './types';
export const CIGARS_DATA: Cigar[] = [
  {
    id: 1,
    name: 'ANTONIO GIMENEZ CHURCHILL',
    image: '/images/ANTONIO GIMENEZ CHURCHILL.png',
    detailsImage: '/images/ANTONIO GIMENEZ CHURCHILL details.png',
    price: '₱1,200.00',
    origin: 'Philippines',
    profile: 'Mild - Medium',
    vitola: '7x47 Churchill',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'An extended format for the full experience, the AG Churchill spans 7" × 47 and delivers consistent richness from foot to nub. Its Java wrapper and Isabela binder encase a premium filler blend that smokes bold and spicy. This long-format cigar is ideal for aficionados craving a classic, uninterrupted full-bodied session.',
  },
  {
    id: 2,
    name: 'COHIBA PURO DOMINICANA ROBUSTO',
    image: '/images/COHIBA PURO DOMINICANA ROBUSTO.png',
    detailsImage: '/images/COHIBA PURO DOMINICANA ROBUSTO details.png',
    price: '₱3,500.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '5.5x50 Robusto',
    wrapper: 'Habano',
    binder: 'Dominican Republic',
    filler: 'Dominican Republic',
    description: 'The Cohiba Puro Dominicana lives up to its name as a 100% Dominican puro. Crafted by master blender Daniel Nunez, this robust cigar begins with an oily, toothsome Dominican Habano wrapper cloaking a Dominican binder and long-filler blend. To maximize flavor, each tobacco leaf is patiently aged en tercio in charcoal-lined barrels, imparting a distinctive oaky taste. Once rolled, the medium-to-full bodied cigar undergoes further aging, allowing its complex flavors to marry. The result is a powerful yet refined balance of leathery spice. As Cohiba\'s definitive super-premium robusto, the Puro Dominicana delivers full-flavored satisfaction down to the nub. Try pairing it with a Spiked Egg Nog for a perfect match.',
  },
  {
    id: 3,
    name: 'DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS',
    image: '/images/DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS.png',
    detailsImage: '/images/DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS details.png',
    price: '₱4,000.00',
    origin: 'Dominican Republic',
    profile: 'Medium',
    vitola: '5 1/4x50 Robusto',
    wrapper: 'Ecuadorian Sungrown',
    binder: 'Dominican Republic',
    filler: 'Dominican Republic',
    description: 'The Davidoff Millennium Blend Series Robusto Tubos harmoniously blends ligero and visus grade leaves, resulting in deep, aromatic notes of cedar, earth, and spice. This expertly crafted cigar features a zesty white-pepper spice that is tempered and complemented by a creamy, earthy undercurrent and a trace of enticing cocoa sweetness. Dressed in a silky, reddish Ecuadorian Sungrown wrapper over a Dominican binder and filler, the Millennium Robusto Tubos will appeal to both novice and veteran cigar enthusiasts. This cigar pairs exceptionally well with a whisky-based cocktail, making it an ideal after-hours indulgence.',
  },
  {
    id: 4,
    name: 'DAVIDOFF WINSTON CHURCHILL ROBUSTO',
    image: '/images/DAVIDOFF WINSTON CHURCHILL ROBUSTO.png',
    detailsImage: '/images/DAVIDOFF WINSTON CHURCHILL ROBUSTO details.png',
    price: '₱3,800.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '5 1/4x52 Robusto',
    wrapper: 'Ecuador',
    binder: 'Negro San Andres, Mexico',
    filler: 'Dominican Republic and Nicaragua',
    description: 'Indulge in the Davidoff Winston Churchill Robusto, where a blend of Dominican Republic, Nicaraguan, and Mexican tobaccos, complemented by an Ecuadorian wrapper, creates a harmonious fusion of leather, cream, spice, and dark coffee flavors, striking a flawless equilibrium between complexity and potency. The hint of cedar\'s natural sweetness in the Davidoff Winston Churchill - "The Original Series" pairs exquisitely with whiskies like Glenmorangie or Macallan Amber, offering a delightful combination of flavors.',
  },
  {
    id: 5,
    name: 'FLOR DE FILIPINAS CORONA SUMATRA',
    image: '/images/FLOR DE FILIPINAS CORONA SUMATRA.png',
    detailsImage: '/images/FLOR DE FILIPINAS CORONA SUMATRA details.png',
    price: '₱800.00',
    origin: 'Philippines',
    profile: 'Mild - Medium',
    vitola: '5.5x44 Corona',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'Classic and aromatic, the Flor De Filipinas Corona Sumatra combines tradition with balance. Measuring 5.5 × 44, it\'s wrapped in a fine Sumatra-grown Java leaf with a signature "Sarah" binder, giving it a slightly sweet edge. Its Isabela-Sarah filler blend produces a mellow yet flavorful smoke—a comforting companion for daily',
  },
  {
    id: 6,
    name: 'INDEPENDENCIA 1898 ROBUSTO',
    image: '/images/INDEPENDENCIA 1898 ROBUSTO.png',
    detailsImage: '/images/INDEPENDENCIA 1898 ROBUSTO details.png',
    price: '₱1,000.00',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: '5x52 Robusto',
    wrapper: 'Indonesia',
    binder: 'Philippines',
    filler: 'Philippines',
    description: 'Celebrating Filipino pride, the 1898 Robusto is a symbol of heritage and flavor. Wrapped in smooth Indonesian Java and filled with rich Isabela "pais" tobacco, it delivers a balanced, full-bodied profile. Measuring 5 × 52, this Robusto offers a creamy smoke with earthy undertones—ideal for both celebratory and contemplative moments.',
  },
  {
    id: 7,
    name: 'Rocky Patel Cargo Torpedo',
    image: '/images/Rocky Patel Cargo Torpedo.png',
    detailsImage: '/images/Rocky Patel Cargo Torpedo details.png',
    price: '₱1,400.00',
    origin: 'Nicaragua',
    profile: 'Medium',
    vitola: '6x52 Torpedo',
    wrapper: 'Ecuador Connecticut',
    binder: 'Nicaragua',
    filler: 'Nicaraguan',
    description: 'The Rocky Patel Cargo Torpedo is a sleeper hit in the Rocky Patel catalog — an accessible, well-constructed cigar that punches above its price point. Draped in a silky Ecuador Sumatra wrapper, it opens with dry cedar and toasted almond notes that quickly deepen into seasoned wood and a faint black-pepper spice. The torpedo tip concentrates the smoke and brings forward an energetic core of cocoa and subtle espresso, while the Nicaraguan filler gives the blend a pleasant earthiness. Construction is consistently reliable, producing a steady draw and an even, long-lasting burn that makes Cargo a dependable daily smoke for both new and experienced smokers.',
  },
  {
    id: 8,
    name: '1881 PERIQUE BOLD SHORT ROBUSTO MADURO',
    image: '/images/1881 PERIQUE BOLD SHORT ROBUSTO MADURO.jpg',
    detailsImage: '/images/1881 PERIQUE BOLD SHORT ROBUSTO MADURO details.jpg',
    price: '₱2,000.00',
    origin: 'Philippines',
    profile: 'Full',
    vitola: '4x55 Robusto',
    wrapper: 'Dominican Republic',
    binder: 'Philippines',
    filler: 'Brazil',
    description: 'Tabacalera proudly presents the 1881 Perique Bold, a premium cigar crafted from a distinctive blend of 15-year vintage tobaccos and rare Louisiana-grown Perique, meticulously fermented in oak whiskey casks to enhance its depth and strength. This innovative fusion delivers a remarkably smooth smoking experience, enriched by bold peppery notes, hints of subtle sweetness, and a long-lingering spice that finishes with refined elegance.',
  },
  {
    id: 9,
    name: 'TABACALERA GRAN RESERVA',
    image: '/images/TABACALERA GRAN RESERVA.jpg',
    detailsImage: '/images/TABACALERA GRAN RESERVA details.jpg',
    price: '₱2,300.00',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: '5x52 Robusto',
    wrapper: 'Philippines',
    binder: 'Philippines',
    filler: 'Philippines, Brazil, Dominican Republic',
    description: 'Crafted for the true cigar aficionado, the Tabacalera Gran Reserva embodies sophistication, heritage, and complexity. Expertly rolled by masters with over 50 years of experience, this exceptional cigar represents the pinnacle of craftsmanship. Its refined blend features Philippine leaf aged for 20 years, harmoniously combined with Brazilian and Dominican tobaccos matured for 15 years. The result is a smooth, luxurious smoke with remarkable depth and a satisfyingly long finish that reveals rich layers of flavor. The Gran Reserva delivers elegant notes of earth, cedar, and a subtle spice—ideal for those long, reflective moments.',
  },
  {
    id: 10,
    name: 'ALEC BRADLEY SUPERSTITION',
    image: '/images/ALEC BRADLEY SUPERSTITION.jpg',
    detailsImage: '/images/ALEC BRADLEY SUPERSTITION.jpg',
    price: '₱1,400.00',
    origin: 'Dominican Republic',
    profile: 'Medium - Full',
    vitola: '6.1x54 Toro Torpedo',
    wrapper: 'Habano / Nicaraguan Jalapa',
    binder: 'Sumatra',
    filler: 'Dominican / Hondura / Nicaragua',
    description: 'A sophisticated blend featuring a Habano wrapper with Nicaraguan Jalapa, complemented by a Sumatra binder and a complex filler blend from Dominican Republic, Honduras, and Nicaragua.',
  },
  {
    id: 11,
    name: 'HC SERIES WHITE SHADE GROWN TORO',
    image: '/images/HC SERIES WHITE SHADE GROWN TORO.jpg',
    detailsImage: '/images/HC SERIES WHITE SHADE GROWN TORO.jpg',
    price: '₱1,400.00',
    origin: 'Honduras',
    profile: 'Mild - Medium',
    vitola: '6x60 Toro',
    wrapper: 'USA Connecticut Shade',
    binder: 'Nicaraguan',
    filler: 'Nicaraguan',
    description: 'The HS Series White Shade Grown features a silky-smooth Connecticut Shade wrapper enveloping a blend of long-filler tobaccos from Nicaragua, providing a mellow-medium body. Subtle notes of leather, cedar, spices, pepper, and caramel mingle throughout the mellow and creamy smoking experience, culminating in a smooth, sweet finish.',
  },
  {
    id: 12,
    name: 'Punch Grand Puro Rancho',
    image: '/images/Punch Grand Puro Rancho.jpg',
    detailsImage: '/images/Punch Grand Puro Rancho.jpg',
    price: '₱1,500.00',
    origin: 'Honduras',
    profile: 'Medium - Full',
    vitola: '5.5x54 Robusto',
    wrapper: 'Honduran (Havana Seed)',
    binder: 'Honduran',
    filler: 'Honduran',
    description: 'Punch is one of the original cigar brands developed in Honduras, proudly reflecting the country\'s long-standing tradition of expert tobacco curing. True to its name, the Punch Gran Puro Rancho delivers a bold, full-flavored smoking experience. Crafted handmade entirely from premium Honduran tobacco, this robusto offers rich, earthy, and creamy notes, wrapped in a striking Colorado Maduro wrapper. Expect a smooth yet intense profile, as flavors of cedar and earth meld seamlessly with the signature Honduran spice—making it an ideal choice for fans of fuller-bodied cigars.',
  },
  {
    id: 13,
    name: 'OLIVA SAISON MADURO TORO',
    image: '/images/OLIVA SAISON MADURO TORO.jpg',
    detailsImage: '/images/OLIVA SAISON MADURO TORO.jpg',
    price: '₱1,500.00',
    origin: 'Nicaragua',
    profile: 'Medium - Full',
    vitola: '6x50 Toro',
    wrapper: 'Connecticut Broadleaf Maduro',
    binder: 'Nicaraguan',
    filler: 'Nicaraguan',
    description: 'Seeking to elevate the strength and complexity of their highly acclaimed Saison line, the team at Oliva took on the challenge—and delivered with the exceptional Oliva Saison Maduro. This bold creation features a meticulously aged blend of Nicaraguan long-fillers, all harvested in 2011 from only the finest tobacco crops grown on Oliva\'s own farms. These tobaccos are expertly bound with a premium Nicaraguan binder and finished with a dark, toothy, and robust Broadleaf Maduro wrapper that enhances both body and character. The result is a rich and harmoniously layered smoking experience, offering deep notes of cedar, sweet spice, and leather, all carried by a consistently razor-sharp burn. True to Oliva\'s reputation, the construction is flawless—firm to the touch with an even, slow draw. Medium to full-bodied in strength, Oliva Saison Maduro is an ideal companion to a glass of rye whiskey, making it a perfect choice for the discerning aficionado seeking depth, balance, and refinement.',
  }
];
