import { Cigar } from './types';

export const CIGARS_DATA: Cigar[] = [
  {
    id: 1,
    name: 'ANTONIO GIMENEZ CHURCHILL',
    image: '/images/ANTONIO GIMENEZ CHURCHILL.png',
    price: '₱',
    origin: 'Nicaragua',
    profile: 'Medium-Full',
    vitola: 'Churchill',
    wrapper: 'Ecuadorian',
    binder: 'Nicaragua',
    filler: 'Nicaragua',
    description: 'The Antonio Gimenez Churchill offers a sophisticated smoking experience with its expertly crafted blend. This premium cigar features an elegant Ecuadorian wrapper that houses choice Nicaraguan tobaccos, delivering a harmonious medium to full-bodied profile.',
  },
  {
    id: 2,
    name: 'COHIBA PURO DOMINICANA ROBUSTO',
    image: '/images/COHIBA PURO DOMINICANA ROBUSTO.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Medium-Full',
    vitola: 'Robusto',
    wrapper: 'Dominican',
    binder: 'Dominican',
    filler: 'Dominican',
    description: 'A testament to Dominican craftsmanship, the Cohiba Puro Dominicana Robusto is a pure expression of Dominican tobacco. This all-Dominican blend offers a refined smoking experience with perfect construction and balanced flavors.',
  },
  {
    id: 3,
    name: 'DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS',
    image: '/images/DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Full',
    vitola: 'Robusto Tubos',
    wrapper: 'Ecuadorian Sun Grown',
    binder: 'Dominican',
    filler: 'Dominican',
    description: 'The Davidoff Millennium Blend Robusto Tubos represents luxury and sophistication. Packaged in an elegant tube, this cigar features an Ecuadorian Sun Grown wrapper that adds depth to its complex profile of perfectly aged Dominican tobaccos.',
  },
  {
    id: 4,
    name: 'DAVIDOFF WINSTON CHURCHILL ROBUSTO',
    image: '/images/DAVIDOFF WINSTON CHURCHILL ROBUSTO.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Medium',
    vitola: 'Robusto',
    wrapper: 'Ecuadorian',
    binder: 'Mexican',
    filler: 'Dominican & Nicaraguan',
    description: 'Named after the legendary statesman, the Davidoff Winston Churchill Robusto embodies sophistication and character. This masterfully crafted cigar combines Dominican and Nicaraguan tobaccos to create a complex and refined smoking experience.',
  },
  {
    id: 5,
    name: 'FLOR DE FILIPINAS CORONA SUMATRA',
    image: '/images/FLOR DE FILIPINAS CORONA SUMATRA.png',
    price: '₱',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: 'Corona',
    wrapper: 'Sumatra',
    binder: 'Philippine',
    filler: 'Philippine',
    description: 'A proud product of Philippine tobacco craftsmanship, the Flor de Filipinas Corona Sumatra features a beautiful Sumatra wrapper encompassing choice Philippine tobaccos. This cigar represents the rich heritage of Philippine cigar making.',
  },
  {
    id: 6,
    name: 'INDEPENDENCIA 1898 ROBUSTO',
    image: '/images/INDEPENDENCIA 1898 ROBUSTO.png',
    price: '₱',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: 'Robusto',
    wrapper: 'Philippine',
    binder: 'Philippine',
    filler: 'Philippine',
    description: 'The Independencia 1898 Robusto pays homage to Philippine independence with an all-Philippine tobacco blend. This cigar showcases the quality of locally grown tobaccos and the expertise of Filipino cigar makers.',
  },
  {
    id: 7,
    name: 'Rocky Patel Cargo Torpedo',
    image: '/images/Rocky Patel Cargo Torpedo.png',
    price: '₱',
    origin: 'Nicaragua',
    profile: 'Medium',
    vitola: 'Torpedo',
    wrapper: 'Ecuador Connecticut',
    binder: 'Nicaragua',
    filler: 'Nicaragua',
    description: 'The Rocky Patel Cargo Torpedo features a distinctive torpedo shape that concentrates flavors and enhances the smoking experience. Wrapped in an Ecuador Connecticut leaf, this cigar delivers a balanced medium-bodied profile with Nicaraguan character.',
  },
  {
    id: 8,
    name: '1881 PERIQUE BOLD SHORT ROBUSTO MADURO',
    image: '/images/1881 PERIQUE BOLD SHORT ROBUSTO MADURO.jpg',
    price: '₱2,000.00',
    origin: 'Philippines',
    profile: 'Full',
    vitola: '4x55 Robusto',
    wrapper: 'Dominican Republic',
    binder: 'Philippines',
    filler: 'Brazil',
    description: 'Tabacalera proudly presents the 1881 Perique Bold, a premium cigar crafted from a distinctive blend of 15-year vintage tobaccos and rare Louisiana-grown Perique, meticulously fermented in oak whiskey casks to enhance its depth and strength. This innovative fusion delivers a remarkably smooth smoking experience, enriched by bold peppery notes, hints of subtle sweetness, and a long-lingering spice that finishes with refined elegance.',
  },
  {
    id: 9,
    name: 'TABACALERA GRAN RESERVA',
    image: '/images/TABACALERA GRAN RESERVA.jpg',
    price: '₱2,300.00',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: '5x52 Robusto',
    wrapper: 'Philippines',
    binder: 'Philippines',
    filler: 'Philippines, Brazil, Dominican Republic',
    description: 'Crafted for the true cigar aficionado, the Tabacalera Gran Reserva embodies sophistication, heritage, and complexity. Expertly rolled by masters with over 50 years of experience, this exceptional cigar represents the pinnacle of craftsmanship. Its refined blend features Philippine leaf aged for 20 years, harmoniously combined with Brazilian and Dominican tobaccos matured for 15 years. The result is a smooth, luxurious smoke with remarkable depth and a satisfyingly long finish that reveals rich layers of flavor.',
  },
  {
    id: 10,
    name: 'FLAVORED PANETELAS CHERRY',
    image: '/images/FLAVORED PANETELAS CHERRY.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'N/A',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Fragrant, fruity, and pleasantly smooth, Flor de Filipinas Cherry Panetela is a vibrant choice for those who enjoy a sweeter, more playful smoking experience. It\'s a flavorful companion to breezy afternoons or relaxed hangouts.',
  },
  {
    id: 11,
    name: 'FLAVORED PANETELAS CHOCOLATE',
    image: '/images/FLAVORED PANETELAS CHOCOLATE.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'Java',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Richly aromatic and indulgently smooth, Flor de Filipinas Chocolate Panetela is a cocoa-infused treat designed for those who enjoy sweet, full-flavored smokes. A satisfying companion to coffee, dessert, or a cozy evening unwind.',
  },
  {
    id: 12,
    name: 'FLAVORED PANETELAS HONEY',
    image: '/images/FLAVORED PANETELAS HONEY.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'N/A',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Delicately sweet and incredibly smooth, Flor de Filipinas Honey Panetela offers a gentle, golden flavor profile that\'s easy to love. Mellow with a golden nectar finish, the Honey Panetela offers a smooth draw and subtle sweetness.',
  },
  {
    id: 13,
    name: 'FLAVORED PANETELAS SPICE RUM',
    image: '/images/FLAVORED PANETELAS SPICE RUM.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'N/A',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Warm, aromatic, and full of character, Flor de Filipinas Spice Rum Panetela brings a spirited twist to the traditional cigar. Infused with notes of clove and molasses, this 5 × 35 Panetela delivers the richness of rum in a mellow, satisfying format.',
  },
  {
    id: 14,
    name: 'FLAVORED PANETELAS VANILLA',
    image: '/images/FLAVORED PANETELAS VANILLA.jpg',
    price: '₱300.00',
    origin: 'Philippines',
    profile: 'Mild',
    vitola: '5x35 Panetela',
    wrapper: 'N/A',
    binder: 'N/A',
    filler: 'N/A',
    description: 'Aromatic, flavorful, and delightfully smooth, Flor de Filipinas Vanilla Panetela delivers a light, creamy smoke with a sweet vanilla crème finish. Whether you\'re new to cigars or simply craving a dessert-like indulgence, this petite cigar is a satisfying, aromatic treat.',
  },
];