import { Cigar } from './types';

export const CIGARS_DATA: Cigar[] = [
  {
    id: 1,
    name: 'ANTONIO GIMENEZ CHURCHILL',
    image: '/images/ANTONIO GIMENEZ CHURCHILL.png',
    detailsImage: '/images/ANTONIO GIMENEZ CHURCHILL details.png',
    price: '₱',
    origin: 'Nicaragua',
    profile: 'Medium-Full',
    vitola: 'Churchill',
    wrapper: 'Ecuadorian',
    binder: 'Nicaragua',
    filler: 'Nicaragua',
    description: 'The Antonio Gimenez Churchill offers a sophisticated smoking experience with its expertly crafted blend. This premium cigar features an elegant Ecuadorian wrapper that houses choice Nicaraguan tobaccos, delivering a harmonious medium to full-bodied profile.',
  },
  {
    id: 2,
    name: 'COHIBA PURO DOMINICANA ROBUSTO',
    image: '/images/COHIBA PURO DOMINICANA ROBUSTO.png',
    detailsImage: '/images/COHIBA PURO DOMINICANA ROBUSTO details.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Medium-Full',
    vitola: 'Robusto',
    wrapper: 'Dominican',
    binder: 'Dominican',
    filler: 'Dominican',
    description: 'A testament to Dominican craftsmanship, the Cohiba Puro Dominicana Robusto is a pure expression of Dominican tobacco. This all-Dominican blend offers a refined smoking experience with perfect construction and balanced flavors.',
  },
  {
    id: 3,
    name: 'DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS',
    image: '/images/DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS.png',
    detailsImage: '/images/DAVIDOFF MILLENNIUM BLEND ROBUSTO TUBOS details.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Full',
    vitola: 'Robusto Tubos',
    wrapper: 'Ecuadorian Sun Grown',
    binder: 'Dominican',
    filler: 'Dominican',
    description: 'The Davidoff Millennium Blend Robusto Tubos represents luxury and sophistication. Packaged in an elegant tube, this cigar features an Ecuadorian Sun Grown wrapper that adds depth to its complex profile of perfectly aged Dominican tobaccos.',
  },
  {
    id: 4,
    name: 'DAVIDOFF WINSTON CHURCHILL ROBUSTO',
    image: '/images/DAVIDOFF WINSTON CHURCHILL ROBUSTO.png',
    detailsImage: '/images/DAVIDOFF WINSTON CHURCHILL ROBUSTO details.png',
    price: '₱',
    origin: 'Dominican Republic',
    profile: 'Medium',
    vitola: 'Robusto',
    wrapper: 'Ecuadorian',
    binder: 'Mexican',
    filler: 'Dominican & Nicaraguan',
    description: 'Named after the legendary statesman, the Davidoff Winston Churchill Robusto embodies sophistication and character. This masterfully crafted cigar combines Dominican and Nicaraguan tobaccos to create a complex and refined smoking experience.',
  },
  {
    id: 5,
    name: 'FLOR DE FILIPINAS CORONA SUMATRA',
    image: '/images/FLOR DE FILIPINAS CORONA SUMATRA.png',
    detailsImage: '/images/FLOR DE FILIPINAS CORONA SUMATRA details.png',
    price: '₱',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: 'Corona',
    wrapper: 'Sumatra',
    binder: 'Philippine',
    filler: 'Philippine',
    description: 'A proud product of Philippine tobacco craftsmanship, the Flor de Filipinas Corona Sumatra features a beautiful Sumatra wrapper encompassing choice Philippine tobaccos. This cigar represents the rich heritage of Philippine cigar making.',
  },
  {
    id: 6,
    name: 'INDEPENDENCIA 1898 ROBUSTO',
    image: '/images/INDEPENDENCIA 1898 ROBUSTO.png',
    detailsImage: '/images/INDEPENDENCIA 1898 ROBUSTO details.png',
    price: '₱',
    origin: 'Philippines',
    profile: 'Medium',
    vitola: 'Robusto',
    wrapper: 'Philippine',
    binder: 'Philippine',
    filler: 'Philippine',
    description: 'The Independencia 1898 Robusto pays homage to Philippine independence with an all-Philippine tobacco blend. This cigar showcases the quality of locally grown tobaccos and the expertise of Filipino cigar makers.',
  },
  {
    id: 7,
    name: 'Rocky Patel Cargo Torpedo',
    image: '/images/Rocky Patel Cargo Torpedo.png',
    detailsImage: '/images/Rocky Patel Cargo Torpedo details.png',
    price: '₱',
    origin: 'Nicaragua',
    profile: 'Medium',
    vitola: 'Torpedo',
    wrapper: 'Ecuador Connecticut',
    binder: 'Nicaragua',
    filler: 'Nicaragua',
    description: 'The Rocky Patel Cargo Torpedo features a distinctive torpedo shape that concentrates flavors and enhances the smoking experience. Wrapped in an Ecuador Connecticut leaf, this cigar delivers a balanced medium-bodied profile with Nicaraguan character.',
  },
];